# Suggested code may be subject to a license. Learn more: ~LicenseLog:1935519394.
yaml
name: Update gh-pages branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the main branch
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for branches

      # Step 2: Create a temporary folder and copy necessary files
      - name: Copy index.html and static folder
        run: |
          mkdir output
          cp index.html output/
          cp -r static/ output/

      # Step 3: Switch to gh-pages branch and prepare for deployment
      - name: Deploy to gh-pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin gh-pages
          git checkout gh-pages || git checkout --orphan gh-pages
          rm -rf !(output) # Remove everything except the output directory
          cp -r output/* .
          git add .
          git commit -m "Update gh-pages with latest changes from main" || echo "Nothing to commit"
          git push origin gh-pages